source 'https://api.berkshelf.com'
cookbook 'yum-pkg', path: 'yum-pkg'
cookbook 'git'
cookbook 'build-essential'
cookbook 'yum', '~> 3.2.4'
cookbook 'nginx', '~> 2.7.4'
cookbook 'unicorn', '~> 2.0.0'
cookbook 'rbenv', :git => 'git://github.com/fnichol/chef-rbenv.git', :branch => 'v0.7.2'
cookbook 'ruby_build', '~> 0.8.0'
cookbook 'emacs24'
cookbook 'tmux'
cookbook 'nodejs'